# Generated by Django 4.2.4 on 2023-08-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Category', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Image', models.CharField(max_length=300)),
            ],
        ),
    ]
